TYPE = exe
SOURCES = test.cpp
INCLUDES = -I. -I/usr/local/include -I../src
LIBS = ../libHelper.a
INSLIBS = -lpcre
OUT = test

#-----------------------------------------------------------------
include ../build.mk

