TYPE = lib
SOURCES = source1.cpp source2.cpp source3.cpp
INCLUDES = -I$(PWD)/../include -I/usr/local/include
MKDIRS = ../lib
OUT = ../lib/libHelper.a

#-----------------------------------------------------------------
include ../build.mk
